namespace: default
deployment:
  terminationGracePeriodSeconds: 3600
  container:
    generate_node_keys:
      image:
        repository: ethereum/client-go
        tag: alltools-v1.12.0
        pullPolicy: IfNotPresent
    nimbus:
      image:
        repository: statusim/nimbus-eth2
        tag: amd64-v23.5.1
        pullPolicy: IfNotPresent
      resources:
        requests:
          cpu: 1000m
          memory: 6Gi
        limits:
          cpu: 1000m
          memory: 6Gi
    geth:
      commandExtraArgs:
        - --rpc.evmtimeout=5
        - --goerli
        - --authrpc.port={{ .Values.deployment.container.geth.authRpcPort }}
        - --authrpc.jwtsecret=/nimbus-data/jwtsecret
        - --authrpc.vhosts=*
        - --port={{ .Values.deployment.container.geth.networkPort }}
        - --syncmode=full
        - --maxpeers=100
        - --http.vhosts={{ .Values.deployment.container.geth.rpcVhosts }}
        - --http.corsdomain='*'
        - --http.api={{ .Values.deployment.container.geth.apiMngt }}
        - --ws.api={{ .Values.deployment.container.geth.apiMngt }}
        - --ws.origins={{ .Values.deployment.container.geth.wsOrigins }}
        - --rpc.txfeecap=100
        - --rpc.gascap=500000000
      image:
        repository: ethereum/client-go
        tag: v1.12.0
        pullPolicy: IfNotPresent
      resources:
        requests:
          cpu: 2600m
          memory: 10Gi
        limits:
          cpu: 3600m
          memory: 12Gi

service:
  authRpcPort: 8551
  nimbus:
    ports:
      p2pPort: 9000
      restPort: 5052  
  geth:
    ports:
      rpcPort: 8545
      wsPort: 8546
      networkPort: 30303

pvc:
  nimbus:
    resource:
      request: 200Gi
  geth:
    resource:
      request: 360Gi

configmap:
  trieTimeout: 3600000000000
  rpcReadTimeout: 30000000000
  rpcWriteTimeout: 30000000000
  rpcIdleTimeout: 120000000000
