apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
{{ include "labels.commons" . | indent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
    - name: rpc
      port: {{ .Values.service.geth.ports.rpcPort }}
    - name: ws
      port: {{ .Values.service.geth.ports.wsPort }}
  selector:
{{ include "labels.commons" . | indent 4 }}